name: CI

on:
  - pull_request
  - push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: if [ -z ${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json') }} ]; then npm install; else npm ci; fi;
        name: npm install
      - run: npx xo

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: if [ -z ${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json') }} ]; then npm install; else npm ci; fi;
        name: npm install
      - run: npm run build

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: if [ -z ${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json') }} ]; then npm install; else npm ci; fi;
        name: npm install
      - run: npx ava
